---
title: 단순회귀분석 01
author: Matt
date: '2020-04-05'
slug: using-r-markdown
categories: []
tags: []
---

# 단순회귀모델에 대한 회귀함수 추정

이번 포스팅에서는 가장 중요한 시작이 되는 단순회귀모델 자체에 대해서 살펴 보겠습니다.

## 1. 단순회귀모델

#### 1.1 모델의 형태

단순회귀모델의 형태는 다음과 같습니다.
$$ y_i = \beta_0 + \beta_1x_i + \epsilon_i$$

#### 1.2 모델의 각 항에 대한 설명

 - $y_i$는 $i$번째 trial에 대한 응답(종속)변수입니다.
 - $\beta_0$ 과 $\beta_1$는 모수입니다.
 - $x_i$는 알고 있는 상수로 $i$번째 trial에 대한 예측(독립)변수입니다.

$\epsilon_i$는 random error항인데 확률변수입니다. 그리고 다음의 내용을 가정합니다.

 - $E[\epsilon_i]$ = 0
 - $\sigma^2[\epsilon_i]=\sigma^2$
 - $\epsilon_i$ 와 $\epsilon_j$는 비상관입니다. 그러므로 $\epsilon_i$ 와 $\epsilon_j$의 공분산은 0입니다. 예를들어 $\sigma[\epsilon_i,\epsilon_j] = 0$, $i\neq j$

## 2. 단순회귀모델에 대한 기댓값과 분산
선형성과 모델에 대한 가정에 의해
$$E[y_i] = E[\beta_0 + \beta_1x_i + \epsilon_i] = \beta_0 + \beta_1x_i + E[\epsilon_i] = \beta_0 + \beta_1x_i$$

여기서  $E[y_i] = \beta_0 + \beta_1x_i$ 가 바로 단순회귀모델에 대한 회귀함수입니다.

$$\sigma^2[y_i] = \sigma^2[\beta_0 + \beta_1x_i + \epsilon_i] = \sigma^2$$

## 3. 모델에 대한 주요 포인트

 - 단순회귀모델인 $y_i = \beta_0 + \beta_1x_i + \epsilon_i$는 수학적 함수관계(인과관계)가 아닌 통계적 관계입니다.
 - 단순회귀모델이 통계적 관계인 이유는 $\epsilon_i$가 확률변수 이며 그로 인해서 단순회귀모델 자체가 확률변수이기 때문입니다.
 - $\epsilon_i$ 와 $\epsilon_j$가 비상관이기 때문에 $y_i$와 $y_j$도 비상관입니다. 또한 이 것은 단순회귀모델인 $y_i$ 항 역시 $\epsilon_i$항과 마찬가지로 확률변수 임을 의미합니다.
 - 즉, 이것은 2.번에서 유도된 내용에 의해 응답변수 $y_i$에 대한 확률분포함수의 평균은 $E[y_i] = \beta_0 + \beta_1x_i$ 이며 분산은 $\sigma^2$ 입니다. 
 - 모든 $x_i$ trial에 대해서 분산이 $\sigma^2$로 일정하며 $E[y_i]$는 $x_i$ trial 마다 값이 같거나 다를 수 있습니다.(일반적으로 값이 다릅니다.)
 - 임의의 $y_i$ 와 $y_j$에 대해서 언제나 비상관입니다.

## 4. 예제

어떤 학교의 학생의 수학 공부 시간과 점수에 대한 단순회귀모델이 다음과 같다고 가정 해 보겠습니다. $$ y_i = 10+ 20x_i + \epsilon_i$$
이 모델에서 x는 공부한 시간(단위 한시간), y는 점수를 나타냅니다.

그러면 모델로 부터 다음과 같은 회귀함수를 얻을 수 있습니다.(2.번 참조)
$$E[y_i] = 10+ 20x_i$$

이 때 i번째 에 대응되는 $x,y$ 데이터 값을 $x_i = 2$와 $y_i = 55$ 라고 가정 하겠습니다.
이 때 회귀함수로 얻을 수 있는 값은 $$E[y_i] = 10+ 20*(2) = 50$$ 과 같으므로 이 때의 error term 값 $\epsilon_i$ = 5 입니다. 이것을 회귀모델로 다시 표현해 보면
$$ y_i = 10 + 20*(2) + 5 = 55 $$ 입니다.

즉,  $Y_i=55$ 이며 $E[Y_i] = 50$ 입니다. 자연스럽게 $\epsilon_i = Y_i - E[Y_i]$ 관계를 확인 할 수 있습니다. $\epsilon_i$를 오차(Error)라고 부릅니다.

## 5. 회귀모델에서 모수와 변수의 의미

 - 회귀모델에서 $\beta_0$ 와 $\beta_1$을 회귀계수 라고 부릅니다.
 - $\beta_1$은 회귀함수에서의 기울기입니다. 그렇기 때문에 이것은 x의 단위 증가분 당 y에 대한 확률분포의 평균의 변화량을 나타 냅니다.
 - $\beta_0$는 회귀함수의 $y$절편입니다. 회귀모델의 범위가 $x=0$을 포함 하고 있을 때 $x=0$에서의 $y$에 대한 확률분포의 평균이 $\beta_0$입니다.

다시 4.의 회귀함수를 보겠습니다. $$E[y] = 10+ 20x = 50$$

 - $\beta_1$ = 20은 한 시간 공부 했을 때(즉, x의 단위) 20점에 대한 y의 확률분포의 평균의 증가량을 의미합니다.
 - $\beta_0$ = 10은 0 시간 공부 했을 때(즉, x의 단위) 10점에 대한 y의 확률분포의 평균을 의미 합니다. 하지만 회귀함수를 생성하기 위한 x데이터의 범위(scope)가 0을 제외한 양수값 이라면 $\beta_0$의 본질적으로 현실에서의 어떠한 의미를 반영하지 않습니다.(이 회귀모델에서는 학생들이 최소 0시간을 초과해서 공부한 상황)
 
다음 포스팅에서는 이 내용에 이어서 Alternative Versions of Regression Model과 회귀함수의 추정에 대해서 알아 보겠습니다.

===================================================================================================
정상적인 공유기능을 활용한 공유가 아닌 화면 캡쳐 및 강제로 복사 및 붙여 넣기 식의 공유를 일체 하지 말아 주세요. 출처를 밝힌다고 해도 화면 캡쳐 및 강제로 복사 및 붙여 넣기 식의 공유를 절대 금지합니다.

정상적인 공유기능을 활용한 공유는 컨텐츠 제작자들이 계속해서 컨텐츠를 생성 하는데 큰 도움이 됩니다.